### ISSUE TITLE
Upgrade to Python 3.8

### ISSUE THREAD

**Issue by Dromadon** [Dromadon/hallebarde#20]
We should upgrade to Python 3.8. This will allow us to use a `dataclass` for the `Exchange` class in the domain

**Comment by Mehdi-H** [comment]
Definition of Done:

- [ ] Set python version to 3.8 in the pipfile
- [ ] Set python version to 3.8 in Terraform (for lambda runtime) and deploy infra
- [ ] make sure tests are still passing with `make unit_tests`
- [ ] make sure func tests are still passing with new infra deployed with `make func_tests`
- [ ] change python version in the `.github/workflows/main.yml` CI file
```
with:
          python-version: 3.7  # --> 3.8
```
- [ ] make sure the CI is still green with python 3.8
